Add nonce key param on all wallets
etherspot/etherspot-prime-sdk pull request #101
Opened 2024-02-07 12:15 UTC by 0xSulpiride

## Description

- Added nonce key param for SimpleAccount and ZeroDev wallets

## Types of changes
What types of changes does your code introduce?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Further comments (optional)

-

2024-02-07 12:35 UTC, ch4r10t33r approved these changes
Pls remove and then merge.

2024-02-08 13:59 UTC, arddluma requested changes
pls update date on the changelog and type of change in readme 🗿

2024-02-08 14:05 UTC, arddluma commented on CHANGELOG.md
> +## [1.5.1] - 2024-01-26
^

2024-02-08 14:50 UTC, arddluma approved these changes
LGTM

2024-02-08 15:00 UTC, merged