PRO-2196 - Added ARKA wrapper as sub package
etherspot/etherspot-prime-sdk pull request #110
Opened 2024-03-18 20:06 UTC by vignesha22

## Description

- Added ARKA apis as a sub package module

## Types of changes
What types of changes does your code introduce?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Further comments (optional)

-

2024-03-18 20:16 UTC, ch4r10t33r requested changes

2024-03-18 20:16 UTC, ch4r10t33r commented on src/sdk/paymaster/provider/arka.ts
> +  async getTokenPaymasterAddress(tokenSym: string) {
Pls add comments prior to each method describing what they do.

2024-03-18 20:16 UTC, ch4r10t33r commented on src/sdk/paymaster/provider/arka.ts
> +    const entryPointAddress = '0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789';
We need to make Arka compatible for both EP0.6.0 and EP0.7.0, so rename this variable as entryPointAddressV6.

2024-03-19 11:55 UTC, ch4r10t33r approved these changes
lgtm

2024-03-20 06:37 UTC, kaushalrajbacancy approved these changes
LGTM

2024-03-20 06:55 UTC, merged