ft: adding support of sign typed data along with eip 6942
etherspot/etherspot-prime-sdk pull request #138
Opened 2024-12-20 18:55 UTC by nikhilkumar1612

## Description

- added and tested sign typed data support along with eip 6942.

## Types of changes
What types of changes does your code introduce?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Further comments (optional)

- Sigature for private key injected wallet and metamask for an undeployed wallet:
<img width="553" alt="Screenshot 2024-12-21 at 12 17 31 AM" src="https://github.com/user-attachments/assets/de2ab2ba-9684-49e2-beb4-a24e89323131" />

- Signature for private key injected wallet and metamask for a deployed wallet:
<img width="919" alt="Screenshot 2024-12-21 at 12 15 55 AM" src="https://github.com/user-attachments/assets/f931e981-8022-4eca-9acf-16b28452639c" />
<img width="559" alt="Screenshot 2024-12-21 at 12 16 12 AM" src="https://github.com/user-attachments/assets/41fd8daa-2b23-4d18-9bff-e1f37a276f36" />

2024-12-20 18:57 UTC, ch4r10t33r approved these changes
LGTM

2024-12-21 10:20 UTC, vignesha22 requested changes

2024-12-21 10:20 UTC, vignesha22 commented on src/sdk/wallet/providers/wallet-connect.wallet-provider.ts
>      throw new Error('Not supported on this provider')
Pls change this to a valid one you can see the modularSdk for execution

2024-12-22 10:15 UTC, vignesha22 reviewed
LGTM

2024-12-23 15:28 UTC, vignesha22 approved these changes

2024-12-23 15:29 UTC, merged