feat: concurrent userops & example
etherspot/etherspot-prime-sdk pull request #97
Opened 2024-01-25 13:52 UTC by 0xSulpiride

## Description

- feat: `key` param in `sdk.estimate` function that to make use all values of semi-abstraced nonce that allows to send many userops from one wallet at once

## Types of changes
What types of changes does your code introduce?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Further comments (optional)

-

2024-01-25 13:55 UTC, ch4r10t33r approved these changes
LGTM

2024-01-25 15:48 UTC, vignesha22 requested changes
Just a minor change on versioning

2024-01-25 15:48 UTC, vignesha22 commented on package.json
> +  "version": "1.5.2",
Can you change this to 1.5.0 please

2024-01-26 14:15 UTC, arddluma approved these changes

2024-01-26 15:30 UTC, vignesha22 approved these changes
LGTM

2024-01-29 09:53 UTC, merged