PRO-2136 - Bundler Api Key
etherspot/etherspot-prime-sdk pull request #99
Opened 2024-01-30 08:18 UTC by vignesha22

## Description

- Added `etherspotBundlerApiKey` optional parameter in SdkOptions for use of predefined mainnet bundlers

## Types of changes
What types of changes does your code introduce?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Further comments (optional)

-

2024-01-30 10:42 UTC, lbw33 approved these changes

2024-02-01 09:24 UTC, ch4r10t33r approved these changes
LGTM

2024-02-05 14:58 UTC, ch4r10t33r approved these changes

2024-02-12 10:25 UTC, arddluma requested changes
Could we please add in readme that this is public API key with rate limits, to get higher limits register to https://portal.etherspot.io

2024-02-12 18:55 UTC, arddluma approved these changes

2024-02-12 18:56 UTC, merged